version: '3.8'

services:
  db:
    image: mysql:8.0  
    container_name: panggyo-mysql
    restart: always
    volumes:
      -  ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql  
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb

  node-app:
    build:
      context: .
      dockerfile: node-app/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: pass
      DB_NAME: mydb

volumes:
  mysql_data:  # ✅ 볼륨 정의 추가 (오류 해결)
